#!/bin/sh
ATPORT=2
#Quectel
lte_bw() {
    BW=$(echo "$BW" | grep -o "[0-5]")
    case $BW in
        "0") BW="1.4" ;;
        "1") BW="3" ;;
        "2"|"3"|"4"|"5") BW=$((BW * 5 - 5)) ;;
    esac
}
#Quectel
nr_bw() {
    BW=$(echo "$BW" | grep -o "[0-9]{1,2}")
    case $BW in
        "0"|"1"|"2"|"3"|"4"|"5") BW=$((BW * 5 + 5)) ;;
        "6"|"7"|"8"|"9"|"10"|"11"|"12") BW=$(((BW - 2) * 10)) ;;
        "13") BW="200" ;;
        "14") BW="400" ;;
    esac
}

All_CSQ() {
    Debug "All_CSQ"
    OX=$(sendat $ATPORT "AT+CSQ" | grep "+CSQ:")
    CSQ=$(echo "$OX" | tr 'a-z' 'A-Z' | grep -o "+CSQ: [0-9]{1,2}" | grep -o "[0-9]{1,2}")
    
    if [ "$CSQ" = "99" ]; then
        CSQ=""
    fi

    if [ -n "$CSQ" ]; then
        CSQ_PER=$((CSQ * 100 / 31))"%"
        CSQ_RSSI=$((CSQ * 2 - 113))" dBm"
    else
        CSQ="-"
        CSQ_PER="-"
        CSQ_RSSI="-"
    fi
}

Quectel_SIMINFO() {
    Debug "Quectel_SIMINFO"
    
    # 获取IMEI
    IMEI=$(sendat $ATPORT "AT+CGSN" | awk 'NR==2')

    # 获取IMSI
    IMSI=$(sendat $ATPORT "AT+CIMI" | awk 'NR==2')

    # 获取ICCID
    ICCID=$(sendat $ATPORT "AT+ICCID" | grep -o "+ICCID: [-0-9]*" | grep -o "[-0-9]\{1,4\}")

    # 获取电话号码
    phone=$(sendat $ATPORT "AT+CNUM" | grep "+CNUM:")
}

Quectel_Cellinfo()
{
    # return
    #cellinfo0.gcom
    OX1=$( sendat $ATPORT "AT+COPS=3,0;+COPS?")
    OX2=$( sendat $ATPORT "AT+COPS=3,2;+COPS?")
    OX=$OX1" "$OX2

    #cellinfo.gcom
    OY1=$( sendat $ATPORT "AT+CREG=2;+CREG?;+CREG=0")
    OY2=$( sendat $ATPORT "AT+CEREG=2;+CEREG?;+CEREG=0")
    OY3=$( sendat $ATPORT "AT+C5GREG=2;+C5GREG?;+C5GREG=0")
    OY=$OY1" "$OY2" "$OY3


    OXx=$OX
    OX=$(echo $OX | tr 'a-z' 'A-Z')
    OY=$(echo $OY | tr 'a-z' 'A-Z')
    OX=$OX" "$OY

    #Debug "$OX"
    #Debug "$OY"

    COPS="-"
    COPS_MCC="-"
    COPS_MNC="-"
    COPSX=$(echo $OXx | grep -o "+COPS: [01],0,.\+," | cut -d, -f3 | grep -o "[^\"]\+")

    if [ "x$COPSX" != "x" ]; then
        COPS=$COPSX
    fi

    COPSX=$(echo $OX | grep -o "+COPS: [01],2,.\+," | cut -d, -f3 | grep -o "[^\"]\+")

    if [ "x$COPSX" != "x" ]; then
        COPS_MCC=${COPSX:0:3}
        COPS_MNC=${COPSX:3:3}
        if [ "$COPS" = "-" ]; then
            COPS=$(awk -F[\;] '/'$COPS'/ {print $2}' $ROOTER/signal/mccmnc.data)
            [ "x$COPS" = "x" ] && COPS="-"
        fi
    fi

    if [ "$COPS" = "-" ]; then
        COPS=$(echo "$O" | awk -F[\"] '/^\+COPS: 0,0/ {print $2}')
        if [ "x$COPS" = "x" ]; then
            COPS="-"
            COPS_MCC="-"
            COPS_MNC="-"
        fi
    fi
    COPS_MNC=" "$COPS_MNC

    OX=$(echo "${OX//[ \"]/}")
    CID=""
    CID5=""
    RAT=""
    REGV=$(echo "$OX" | grep -o "+C5GREG:2,[0-9],[A-F0-9]\{2,6\},[A-F0-9]\{5,10\},[0-9]\{1,2\}")
    if [ -n "$REGV" ]; then
        LAC5=$(echo "$REGV" | cut -d, -f3)
        LAC5=$LAC5" ($(printf "%d" 0x$LAC5))"
        CID5=$(echo "$REGV" | cut -d, -f4)
        CID5L=$(printf "%010X" 0x$CID5)
        RNC5=${CID5L:1:6}
        RNC5=$RNC5" ($(printf "%d" 0x$RNC5))"
        CID5=${CID5L:7:3}
        CID5="Short $(printf "%X" 0x$CID5) ($(printf "%d" 0x$CID5)), Long $(printf "%X" 0x$CID5L) ($(printf "%d" 0x$CID5L))"
        RAT=$(echo "$REGV" | cut -d, -f5)
    fi
    REGV=$(echo "$OX" | grep -o "+CEREG:2,[0-9],[A-F0-9]\{2,4\},[A-F0-9]\{5,8\}")
    REGFMT="3GPP"
    if [ -z "$REGV" ]; then
        REGV=$(echo "$OX" | grep -o "+CEREG:2,[0-9],[A-F0-9]\{2,4\},[A-F0-9]\{1,3\},[A-F0-9]\{5,8\}")
        REGFMT="SW"
    fi
    if [ -n "$REGV" ]; then
        LAC=$(echo "$REGV" | cut -d, -f3)
        LAC=$(printf "%04X" 0x$LAC)" ($(printf "%d" 0x$LAC))"
        if [ $REGFMT = "3GPP" ]; then
            CID=$(echo "$REGV" | cut -d, -f4)
        else
            CID=$(echo "$REGV" | cut -d, -f5)
        fi
        CIDL=$(printf "%08X" 0x$CID)
        RNC=${CIDL:1:5}
        RNC=$RNC" ($(printf "%d" 0x$RNC))"
        CID=${CIDL:6:2}
        CID="Short $(printf "%X" 0x$CID) ($(printf "%d" 0x$CID)), Long $(printf "%X" 0x$CIDL) ($(printf "%d" 0x$CIDL))"

    else
        REGV=$(echo "$OX" | grep -o "+CREG:2,[0-9],[A-F0-9]\{2,4\},[A-F0-9]\{2,8\}")
        if [ -n "$REGV" ]; then
            LAC=$(echo "$REGV" | cut -d, -f3)
            CID=$(echo "$REGV" | cut -d, -f4)
            if [ ${#CID} -gt 4 ]; then
                LAC=$(printf "%04X" 0x$LAC)" ($(printf "%d" 0x$LAC))"
                CIDL=$(printf "%08X" 0x$CID)
                RNC=${CIDL:1:3}
                CID=${CIDL:4:4}
                CID="Short $(printf "%X" 0x$CID) ($(printf "%d" 0x$CID)), Long $(printf "%X" 0x$CIDL) ($(printf "%d" 0x$CIDL))"
            else
                LAC=""
            fi
        else
            LAC=""
        fi
    fi
    REGSTAT=$(echo "$REGV" | cut -d, -f2)
    if [ "$REGSTAT" == "5" -a "$COPS" != "-" ]; then
        COPS_MNC=$COPS_MNC" (Roaming)"
    fi
    if [ -n "$CID" -a -n "$CID5" ] && [ "$RAT" == "13" -o "$RAT" == "10" ]; then
        LAC="4G $LAC, 5G $LAC5"
        CID="4G $CID<br />5G $CID5"
        RNC="4G $RNC, 5G $RNC5"
    elif [ -n "$CID5" ]; then
        LAC=$LAC5
        CID=$CID5
        RNC=$RNC5
    fi
    if [ -z "$LAC" ]; then
        LAC="-"
        CID="-"
        RNC="-"
    fi
}




Quectel_AT()
{
    Debug "Quectel_AT"
    ATPORT

    Quectel_SIMINFO
    All_CSQ
    
    Quectel_Cellinfo

    #
OX=$(sendat $ATPORT 'AT+QENG="servingcell"' | grep "+QENG:")

# 使用 awk 提取 NR_NSA 和 NR_SA
NR_NSA=$(echo "$OX" | awk '/\+QENG: "NR5G-NSA"/')
NR_SA=$(echo "$OX" | awk '/\+QENG: "SERVINGCELL",[^,]+,"NR5G-SA"/')

if [ -n "$NR_NSA" ]; then
    QENG=",,"$(echo "$OX" | awk '/\+QENG: "LTE".*"NR5G-NSA"/ {gsub(/ /, ","); print}')
    QENG5=$(echo "$OX" | awk '/\+QENG: "NR5G-NSA",[0-9]{3},[0-9]{2,3},[0-9]{1,5},-[0-9]{2,5},[-0-9]{1,3},-[0-9]{2,3},[0-9]{1,7},[0-9]{1,3}/')
    
    # 如果 QENG5 为空，则尝试备选的匹配模式
    if [ -z "$QENG5" ]; then
        QENG5=$(echo "$OX" | awk '/\+QENG: "NR5G-NSA",[0-9]{3},[0-9]{2,3},[0-9]{1,5},-[0-9]{2,3},[-0-9]{1,3},-[0-9]{2,3}/ {print $0",,"}')
    fi
elif [ -n "$NR_SA" ]; then
    QENG=$(echo "$NR_SA" | tr " " ",")
    QENG5=$(echo "$OX" | awk '/\+QENG: "SERVINGCELL",[^,]+,"NR5G-SA","[DFT]{3}",[ 0-9]{3,4},[0-9]{2,3},[0-9A-F]{1,10},[0-9]{1,5},[0-9A-F]{2,6},[0-9]{6,7},[0-9]{1,3},[0-9]{1,2},-[0-9]{2,5},-[0-9]{2,3},[-0-9]{1,3}/')
else
    QENG=$(echo "$OX" | awk '/\+QENG: [^ ]+/ {gsub(/ /, ","); print}')
fi


    # Debug "$QENG"
    # Debug "$QENG5"
RAT=$(echo $QENG | awk -F, '{print $4}' | grep -o "[-A-Z5]{3,7}")
case $RAT in
    "GSM")
        MODE="GSM"
        ;;

    "WCDMA")
        MODE="WCDMA"
        CHANNEL=$(echo $QENG | awk -F, '{print $9}')
        RSCP="-$(echo $QENG | awk -F, '{print $12}' | grep -o "[0-9]{1,3}")"
        ECIO="-$(echo $QENG | awk -F, '{print $13}' | grep -o "[0-9]{1,3}")"
        ;;

    "LTE"|"CAT-M"|"CAT-NB")
        MODE=$(echo $QENG | awk -F, '{mode=$5; gsub("\"", "", mode); print mode}')
        MODE=${MODE:-$RAT}
        PCI=$(echo $QENG | awk -F, '{print $9}')
        CHANNEL=$(echo $QENG | awk -F, '{print $10}')
        LBAND=$(echo $QENG | awk -F, '{print $11}' | grep -o "[0-9]{1,3}")
        BW=$(echo $QENG | awk -F, '{print $12}')
        lte_bw
        BWU=$BW
        BW=$(echo $QENG | awk -F, '{print $13}')
        lte_bw
        BWD=${BW:-"unknown"}
        BWU=${BWU:-"unknown"}
        LBAND=${LBAND:+B$LBAND " (Bandwidth $BWD MHz Down | $BWU MHz Up)"}
        RSCP="-$(echo $QENG | awk -F, '{print $15}' | grep -o "[0-9]{1,3}")"
        RSRPLTE=$RSCP
        ECIO="-$(echo $QENG | awk -F, '{print $16}' | grep -o "[0-9]{1,3}")"
        RSSI=$(echo $QENG | awk -F, '{print $17}' | grep -o "-[0-9]{1,3}")
        CSQ_RSSI=${RSSI:-"$RSSI dBm"}
        SINRR=$(echo $QENG | awk -F, '{print $18}' | grep -o "[0-9]{1,3}")
        if [ -n "$SINRR" ] && [ $SINRR -le 25 ]; then
            SINR=$((SINRR * 2 - 20))" dB"
        fi
        if [ -n "$NR_NSA" ]; then
            MODE="LTE/NR EN-DC"
            echo "0" > /tmp/modnetwork
            if [ -n "$QENG5" ] && [ -n "$LBAND" ] && [ "$RSCP" != "-" ] && [ "$ECIO" != "-" ]; then
                PCI=$(echo $QENG5 | awk -F, '{print $4}')
                SCHV=$(echo $QENG5 | awk -F, '{print $8}')
                SLBV=$(echo $QENG5 | awk -F, '{print $9}')
                BW=$(echo $QENG5 | awk -F, '{print $10}' | grep -o "[0-9]{1,3}")
                if [ -n "$SLBV" ]; then
                    LBAND="${LBAND}<br />n${SLBV}"
                    if [ -n "$BW" ]; then
                        nr_bw
                        LBAND="${LBAND} (Bandwidth ${BW} MHz)"
                    fi
                    if [ "$SCHV" -ge 123400 ]; then
                        CHANNEL="${CHANNEL}, ${SCHV}"
                    else
                        CHANNEL="${CHANNEL}, -"
                    fi
                else
                    LBAND="${LBAND}<br />nxx (unknown NR5G band)"
                    CHANNEL="${CHANNEL}, -"
                fi
                RSCP="${RSCP} dBm<br />$(echo $QENG5 | awk -F, '{print $5}')"
                SINRR=$(echo $QENG5 | awk -F, '{print $6}' | grep -o "[0-9]{1,3}")
                if [ -n "$SINRR" ] && [ "$SINRR" -le 30 ]; then
                    SINR="${SINR}<br />$((SINRR * 2 - 20)) dB"
                fi
                ECIO="${ECIO} (4G) dB<br />$(echo $QENG5 | awk -F, '{print $7}') (5G)"
            fi
        fi

        if [ -z "$LBAND" ]; then
            LBAND="-"
        fi

        if [ "$RAT" = "CAT-M" ] || [ "$RAT" = "CAT-NB" ]; then
            LBAND="B$(echo $QENG | awk -F, '{print $11}') ($RAT)"
        fi
        ;;
    "NR5G-SA")
        MODE="NR5G-SA"
        if [ -n "$QENG5" ]; then
            MODE="$RAT $(echo $QENG5 | awk -F, '{gsub(/\"/, ""); print $4}')"
            PCI=$(echo $QENG5 | awk -F, '{print $8}')
            CHANNEL=$(echo $QENG5 | awk -F, '{print $10}')
            LBAND=$(echo $QENG5 | awk -F, '{print $11}')
            BW=$(echo $QENG5 | awk -F, '{print $12}')
            nr_bw
            LBAND="n$LBAND (Bandwidth $BW MHz)"
            RSCP=$(echo $QENG5 | awk -F, '{print $13}')
            ECIO=$(echo $QENG5 | awk -F, '{print $14}')
            if [ "$CSQ_PER" = "-" ]; then
                RSSI=$(rsrp2rssi $RSCP $BW) # 假设有一个函数 rsrp2rssi
                CSQ_PER=$((100 - (($RSSI + 51) * 100/-62)))"%"
                CSQ=$((($RSSI + 113) / 2))
                CSQ_RSSI=$RSSI" dBm"
            fi
            SINRR=$(echo $QENG5 | awk -F, '{print $15}' | grep -o "[0-9]{1,3}")
            if [ -n "$SINRR" ] && [ $SINRR -le 30 ]; then
                SINR=$((SINRR * 2 - 20))" dB"
            fi
        fi
        ;;
esac




# 获取QCA信息
OX=$(sendat $ATPORT "AT+QCAINFO" | grep "+QCAINFO:")
QCA=$(echo "$OX " | grep -o -i "+QCAINFO: \"S[CS]{2}\".*NWSCANMODE" | tr " " ",")

# 获取网络扫描模式信息
OX=$(sendat $ATPORT 'AT+QCFG="nwscanmode"' | grep "+QCFG:")
QNSM=$(echo "$OX" | grep -o -i "+QCFG: \"NWSCANMODE\",[0-9]" | grep -o "[0-9]")

if [ -n "$QNSM" ]; then
    MODTYPE="6"
    case $QNSM in
        "0") NETMODE="1" ;;
        "1") NETMODE="3" ;;
        "2"|"5") NETMODE="5" ;;
        "3") NETMODE="7" ;;
    esac
fi

if [ -n "$QNWP" ]; then
    MODTYPE="6"
    case $QNWP in
        "AUTO") NETMODE="1" ;;
        "WCDMA") NETMODE="5" ;;
        "LTE") NETMODE="7" ;;
        "LTE:NR5G") NETMODE="8" ;;
        "NR5G") NETMODE="9" ;;
    esac
fi



# 获取网络偏好设置
OX=$(sendat $ATPORT 'AT+QNWPREFCFG="mode_pref"' | grep "+QNWPREFCFG:")
QNWP=$(echo $OX | awk -F, '/+QNWPREFCFG: "MODE_PREF"/ {print $2}')

# 获取温度信息
OX=$(sendat $ATPORT 'AT+QTEMP' | grep "+QTEMP:")
# 尝试解析不同的温度格式
if [[ -z "$QTEMP" ]]; then
    QTEMP=$(echo $OX | grep -o -i '+QTEMP: \?"[^,]*,[0-9]\{1,3\}' | grep -o '[0-9]\{1,3\}')
fi
# 如果获取到温度值，则转换为摄氏度格式
if [[ -n "$QTEMP" ]]; then
    CTEMP="${QTEMP}°C"
fi


OX=$(sendat $ATPORT "AT+QRSRP" | grep "+QRSRP:")
QRSRP=$(echo "$OX" | awk -F, '/\+QRSRP:/ {print $1,$2,$3,$4,$5}')

if [ -n "$QRSRP" ] && [ "$RAT" != "WCDMA" ]; then
    read -r QRSRP1 QRSRP2 QRSRP3 QRSRP4 QRSRPtype <<< "$QRSRP"

    if [ "$QRSRPtype" == "NR5G" ]; then
        if [ -n "$NR_SA" ]; then
            RSCP="${QRSRP1} dBm"
            [[ "$QRSRP2" != "-32768" ]] && RSCP1="RxD ${QRSRP2} dBm"
            [[ "$QRSRP3" != "-32768" ]] && RSCP="${RSCP}<br />${QRSRP3} dBm"
            [[ "$QRSRP4" != "-32768" ]] && RSCP1="RxD ${QRSRP4} dBm"
        else
            RSCP="${RSRPLTE}"
            if [ -n "$QRSRP1" ] && [ "$QRSRP1" != "-32768" ]; then
                RSCP="${RSCP} (4G) dBm<br />${QRSRP1}"
                if [ -n "$QRSRP2" ] && [ "$QRSRP2" != "-32768" ]; then
                    RSCP="${RSCP},${QRSRP2}"
                    [[ "$QRSRP3" != "-32768" ]] && RSCP="${RSCP},${QRSRP3}"
                    [[ "$QRSRP4" != "-32768" ]] && RSCP="${RSCP},${QRSRP4}"
                    RSCP="${RSCP} (5G)"
                fi
            fi
        fi
    elif [ "${QRSRP2}${QRSRP3}${QRSRP4}" != "-44-44-44" ] && [ -z "$QENG5" ]; then
        RSCP="${QRSRP1} dBm"
        if [ "${QRSRP3}${QRSRP4}" == "-140-140" ] || [ "${QRSRP3}${QRSRP4}" == "-44-44" ] || [ "${QRSRP3}${QRSRP4}" == "-32768-32768" ]; then
            RSCP1="RxD ${QRSRP2} dBm"
        else
            RSCP="${RSCP} (RxD ${QRSRP2} dBm)<br />${QRSRP3} dBm"
            RSCP1="RxD ${QRSRP4} dBm"
        fi
    fi
fi



}